all:
  vars:
    bastion_ip: 91.99.31.80
  children:
    api:
      hosts:
        prod-api-0:
          ansible_host: 46.224.198.189
        prod-api-1:
          ansible_host: 46.224.198.178
    db:
      hosts:
        prod-db-0:
          ansible_host: 46.224.200.62
