$ANSIBLE_VAULT;1.1;AES256
62336561616166353734303765313363646332646263636534643565633062383630363464393330
6139316439376162643332313031653732303266326264620a333761646239356435303061613930
63346362643234373732383636623133626364396161656535303062333836626137643432323961
3835616633333530370a326264383630643762653166306263656236366566343239306533326538
38313239393835313062323333323933613631656531616636313134366637303339636261316366
31383065663834386539626638346563373362326665616430343930643566373163356266623463
37656561366663653664393834646638616136626165363266613137343332636163663232623037
34613631386633313131
