all:
  vars:
    bastion_ip: 157.90.22.220
  children:
    api:
      hosts:
        dev-api-0:
          ansible_host: 46.224.179.37
        dev-api-1:
          ansible_host: 91.98.134.230
    db:
      hosts:
        dev-db-0:
          ansible_host: 49.13.195.179
